// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4o53lBTn_kW42HfX-6T01XLA4T6MOwnY',
    appId: '1:778695777347:web:fc8900316749bf870d88f6',
    messagingSenderId: '778695777347',
    projectId: 'real-time-data-331a1',
    authDomain: 'real-time-data-331a1.firebaseapp.com',
    databaseURL: 'https://real-time-data-331a1-default-rtdb.firebaseio.com',
    storageBucket: 'real-time-data-331a1.appspot.com',
    measurementId: 'G-LS7D1KEENZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_VlAf6hHolUtFxUs6mx6mxXrh-eXVCus',
    appId: '1:778695777347:android:9b2602c4943ccdef0d88f6',
    messagingSenderId: '778695777347',
    projectId: 'real-time-data-331a1',
    databaseURL: 'https://real-time-data-331a1-default-rtdb.firebaseio.com',
    storageBucket: 'real-time-data-331a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyKXiPrXztPkU7wI1Eeihp8dlrc45gBlQ',
    appId: '1:778695777347:ios:8c6d2fd15d2888450d88f6',
    messagingSenderId: '778695777347',
    projectId: 'real-time-data-331a1',
    databaseURL: 'https://real-time-data-331a1-default-rtdb.firebaseio.com',
    storageBucket: 'real-time-data-331a1.appspot.com',
    iosClientId: '778695777347-1cnkgdgtkr3tg1un43jn4hkad9pukieb.apps.googleusercontent.com',
    iosBundleId: 'com.example.codi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyKXiPrXztPkU7wI1Eeihp8dlrc45gBlQ',
    appId: '1:778695777347:ios:8c6d2fd15d2888450d88f6',
    messagingSenderId: '778695777347',
    projectId: 'real-time-data-331a1',
    databaseURL: 'https://real-time-data-331a1-default-rtdb.firebaseio.com',
    storageBucket: 'real-time-data-331a1.appspot.com',
    iosClientId: '778695777347-1cnkgdgtkr3tg1un43jn4hkad9pukieb.apps.googleusercontent.com',
    iosBundleId: 'com.example.codi',
  );
}
